#- name: stop ntpd
#  service: name=ntpd state=stopped
#- shell: ntpdate 0.ubuntu.pool.ntp.org
#- service: name=ntpd state=started

- name: fail2ban.conf
  copy: src=roles/centos/files/fail2ban-log.conf dest=/etc/fail2ban/fail2ban.d/log.conf force=no
  register: fail2banlogconf
- name: fail2ban.conf
  copy: src=roles/centos/files/fail2ban-ssh.conf dest=/etc/fail2ban/jail.d/sshd.conf force=no
  register: fail2banconf
- name: reload fail2ban
#  when: fail2banlogconf.changed or fail2banconf.changed
  service: name=fail2ban state=reloaded

- name: start fail2ban
  service: name=fail2ban state=started
